#define ALICE_SETTINGS_WITH_DEFAULT_OPTION true

#include "net_stores.h"
#include "map_stores.h"

#include "algorithms/balancing.hpp"
//#include "algorithms/collapse_mapping.hpp"
#include "algorithms/cut_rewrite.hpp"
#include "algorithms/equivalence_checking.hpp"
#include "algorithms/functional_reduction.hpp"
#include "algorithms/fanin_optimization.hpp"
#include "algorithms/lut_mapping.hpp"
#include "algorithms/lut_resynthesis.hpp"
#include "algorithms/map.hpp"
#include "algorithms/mccost.hpp"
#include "algorithms/migcost.hpp"
#include "algorithms/mighty.hpp"
#include "algorithms/minmc.hpp"
#include "algorithms/miter.hpp"
#include "algorithms/print_gates.hpp"
#include "algorithms/refactor.hpp"
#include "algorithms/refactormc.hpp"
#include "algorithms/resubstitute.hpp"
//#include "algorithms/satlut_mapping.hpp"
